# Generated by Django 5.1.2 on 2024-10-30 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numId', models.CharField(max_length=11)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='user_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=80)),
                ('year', models.IntegerField(validators=[django.core.validators.MinLengthValidator(1900), django.core.validators.MaxLengthValidator(2025)])),
                ('plates', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='vehicle_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('request_days', models.IntegerField()),
                ('expected_return_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('entry_date', models.DateField()),
                ('request_status', models.CharField(max_length=80)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=80)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_requests', to='alquiler.user')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_requests', to='alquiler.vehicle')),
            ],
        ),
    ]
